- name: create ec2 and r53
  hosts: localhost                  # Changed from 'local' to 'localhost' (correct host)
  connection: local
  gather_facts: false               # Optional but good for faster runs
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0967adedfb4db3092   # Your security group ID
    zone_id: "Z0948150OFPSYTNVYZOY" # Your hosted zone ID
    domain_name: "akulaanil.fun"
    instances: 
      - mongodb
      - redis
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
        name: "{{ item }}"
        state: absent
        instance_type: t3.micro
        security_groups:                 # Note: plural and list format
          - "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        tags:
          Name: "{{ item }}"
        wait: yes                      # Wait for instance to be running
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the ec2_output
    ansible.builtin.debug:
     msg: "{{ ec2_output }}"


  # - name: print the ec2_output
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_output }}"